import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { CreatePostWizzard } from "~/components/CreatePostWizzard";
import { Feed } from "~/components/Feed";
import { LoadingPage } from "~/components/Loading";
import { Post } from "~/components/Post";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const {
    user,
    isLoaded: isUserLoaded,
    isSignedIn: isUserSignedIn,
  } = useUser();

  // start fetching posts asap
  api.posts.getAll.useQuery();

  if (!isUserLoaded) return <div></div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="w-full border-x border-slate-400 md:max-w-2xl">
          <div className="flex border-b border-slate-400 p-4">
            {isUserSignedIn ? <CreatePostWizzard /> : <SignInButton />}
          </div>
          <Feed />
        </div>
      </main>
    </>
  );
};

export default Home;
